#############################################################################
# Makefile for building: lucid
# Generated by qmake (2.01a) (Qt 4.7.0) on: Thu Apr 21 14:27:30 2011
# Project:  lucid/lucid.pro
# Template: app
# Command: /contrib/projects/qt/qt-4.7.0/bin/qmake -spec /course/cs123/lib/qt/qt-4.7.0/mkspecs/linux-g++ CONFIG+=debug -o Makefile lucid/lucid.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/course/cs123/lib/qt/qt-4.7.0/mkspecs/linux-g++ -Ilucid -I/course/cs123/lib/qt/qt-4.7.0/include/QtCore -I/course/cs123/lib/qt/qt-4.7.0/include/QtGui -I/course/cs123/lib/qt/qt-4.7.0/include -I. -I. -Ilucid -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/course/cs123/lib/qt/qt-4.7.0/lib
LIBS          = $(SUBLIBS)  -L/course/cs123/lib/qt/qt-4.7.0//lib -lQtGui -L/course/cs123/lib/qt/qt-4.7.0//lib -L/usr/X11R6/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /contrib/projects/qt/qt-4.7.0/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = lucid/main.cpp \
		lucid/mainwindow.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		moc_mainwindow.o
DIST          = /contrib/projects/qt/qt-4.7.0/mkspecs/common/g++.conf \
		/contrib/projects/qt/qt-4.7.0/mkspecs/common/unix.conf \
		/contrib/projects/qt/qt-4.7.0/mkspecs/common/linux.conf \
		/contrib/projects/qt/qt-4.7.0/mkspecs/qconfig.pri \
		/contrib/projects/qt/qt-4.7.0/mkspecs/features/qt_functions.prf \
		/contrib/projects/qt/qt-4.7.0/mkspecs/features/qt_config.prf \
		/contrib/projects/qt/qt-4.7.0/mkspecs/features/exclusive_builds.prf \
		/contrib/projects/qt/qt-4.7.0/mkspecs/features/default_pre.prf \
		/contrib/projects/qt/qt-4.7.0/mkspecs/features/debug.prf \
		/contrib/projects/qt/qt-4.7.0/mkspecs/features/default_post.prf \
		/contrib/projects/qt/qt-4.7.0/mkspecs/features/warn_on.prf \
		/contrib/projects/qt/qt-4.7.0/mkspecs/features/qt.prf \
		/contrib/projects/qt/qt-4.7.0/mkspecs/features/unix/thread.prf \
		/contrib/projects/qt/qt-4.7.0/mkspecs/features/moc.prf \
		/contrib/projects/qt/qt-4.7.0/mkspecs/features/resources.prf \
		/contrib/projects/qt/qt-4.7.0/mkspecs/features/uic.prf \
		/contrib/projects/qt/qt-4.7.0/mkspecs/features/yacc.prf \
		/contrib/projects/qt/qt-4.7.0/mkspecs/features/lex.prf \
		/contrib/projects/qt/qt-4.7.0/mkspecs/features/include_source_dir.prf \
		lucid/lucid.pro
QMAKE_TARGET  = lucid
DESTDIR       = 
TARGET        = lucid

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: lucid/lucid.pro  /course/cs123/lib/qt/qt-4.7.0/mkspecs/linux-g++/qmake.conf /contrib/projects/qt/qt-4.7.0/mkspecs/common/g++.conf \
		/contrib/projects/qt/qt-4.7.0/mkspecs/common/unix.conf \
		/contrib/projects/qt/qt-4.7.0/mkspecs/common/linux.conf \
		/contrib/projects/qt/qt-4.7.0/mkspecs/qconfig.pri \
		/contrib/projects/qt/qt-4.7.0/mkspecs/features/qt_functions.prf \
		/contrib/projects/qt/qt-4.7.0/mkspecs/features/qt_config.prf \
		/contrib/projects/qt/qt-4.7.0/mkspecs/features/exclusive_builds.prf \
		/contrib/projects/qt/qt-4.7.0/mkspecs/features/default_pre.prf \
		/contrib/projects/qt/qt-4.7.0/mkspecs/features/debug.prf \
		/contrib/projects/qt/qt-4.7.0/mkspecs/features/default_post.prf \
		/contrib/projects/qt/qt-4.7.0/mkspecs/features/warn_on.prf \
		/contrib/projects/qt/qt-4.7.0/mkspecs/features/qt.prf \
		/contrib/projects/qt/qt-4.7.0/mkspecs/features/unix/thread.prf \
		/contrib/projects/qt/qt-4.7.0/mkspecs/features/moc.prf \
		/contrib/projects/qt/qt-4.7.0/mkspecs/features/resources.prf \
		/contrib/projects/qt/qt-4.7.0/mkspecs/features/uic.prf \
		/contrib/projects/qt/qt-4.7.0/mkspecs/features/yacc.prf \
		/contrib/projects/qt/qt-4.7.0/mkspecs/features/lex.prf \
		/contrib/projects/qt/qt-4.7.0/mkspecs/features/include_source_dir.prf \
		/course/cs123/lib/qt/qt-4.7.0/lib/libQtGui.prl \
		/course/cs123/lib/qt/qt-4.7.0/lib/libQtCore.prl
	$(QMAKE) -spec /course/cs123/lib/qt/qt-4.7.0/mkspecs/linux-g++ CONFIG+=debug -o Makefile lucid/lucid.pro
/contrib/projects/qt/qt-4.7.0/mkspecs/common/g++.conf:
/contrib/projects/qt/qt-4.7.0/mkspecs/common/unix.conf:
/contrib/projects/qt/qt-4.7.0/mkspecs/common/linux.conf:
/contrib/projects/qt/qt-4.7.0/mkspecs/qconfig.pri:
/contrib/projects/qt/qt-4.7.0/mkspecs/features/qt_functions.prf:
/contrib/projects/qt/qt-4.7.0/mkspecs/features/qt_config.prf:
/contrib/projects/qt/qt-4.7.0/mkspecs/features/exclusive_builds.prf:
/contrib/projects/qt/qt-4.7.0/mkspecs/features/default_pre.prf:
/contrib/projects/qt/qt-4.7.0/mkspecs/features/debug.prf:
/contrib/projects/qt/qt-4.7.0/mkspecs/features/default_post.prf:
/contrib/projects/qt/qt-4.7.0/mkspecs/features/warn_on.prf:
/contrib/projects/qt/qt-4.7.0/mkspecs/features/qt.prf:
/contrib/projects/qt/qt-4.7.0/mkspecs/features/unix/thread.prf:
/contrib/projects/qt/qt-4.7.0/mkspecs/features/moc.prf:
/contrib/projects/qt/qt-4.7.0/mkspecs/features/resources.prf:
/contrib/projects/qt/qt-4.7.0/mkspecs/features/uic.prf:
/contrib/projects/qt/qt-4.7.0/mkspecs/features/yacc.prf:
/contrib/projects/qt/qt-4.7.0/mkspecs/features/lex.prf:
/contrib/projects/qt/qt-4.7.0/mkspecs/features/include_source_dir.prf:
/course/cs123/lib/qt/qt-4.7.0/lib/libQtGui.prl:
/course/cs123/lib/qt/qt-4.7.0/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /course/cs123/lib/qt/qt-4.7.0/mkspecs/linux-g++ CONFIG+=debug -o Makefile lucid/lucid.pro

dist: 
	@$(CHK_DIR_EXISTS) lucid/.tmp/lucid1.0.0 || $(MKDIR) lucid/.tmp/lucid1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) lucid/.tmp/lucid1.0.0/ && $(COPY_FILE) --parents lucid/mainwindow.h lucid/.tmp/lucid1.0.0/ && $(COPY_FILE) --parents lucid/main.cpp lucid/mainwindow.cpp lucid/.tmp/lucid1.0.0/ && $(COPY_FILE) --parents lucid/mainwindow.ui lucid/.tmp/lucid1.0.0/ && (cd `dirname lucid/.tmp/lucid1.0.0` && $(TAR) lucid1.0.0.tar lucid1.0.0 && $(COMPRESS) lucid1.0.0.tar) && $(MOVE) `dirname lucid/.tmp/lucid1.0.0`/lucid1.0.0.tar.gz . && $(DEL_FILE) -r lucid/.tmp/lucid1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check:

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: lucid/mainwindow.h
	/course/cs123/lib/qt/qt-4.7.0//bin/moc $(DEFINES) $(INCPATH) lucid/mainwindow.h -o moc_mainwindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: lucid/mainwindow.ui
	/course/cs123/lib/qt/qt-4.7.0/bin/uic lucid/mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: lucid/main.cpp lucid/mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o lucid/main.cpp

mainwindow.o: lucid/mainwindow.cpp lucid/mainwindow.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o lucid/mainwindow.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

